singularms/web/apps/mt/urls.py
# -*- coding: utf-8 -*-

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

from django.conf.urls.defaults import *

urlpatterns = patterns('mt.views',
    
    # Channel stuff
    url(r'^channel/list/$',                      'channelList',      name='showList'),
    url(r'^channel/list/page(?P<page>[0-9]+)/$', 'channelList',      name='showListPage'),
    url(r'^channel/(?P<object_id>\d+)/update/$', 'updateChannel',    name='update_channel'),
    url(r'^channel/(?P<object_id>\d+)/delete/$', 'deleteChannel',    name='delete_channel'),
    url(r'^channel/subscriber/$',                'showSubscriber',   name='showSubscriber'),
    url(r'^channel/subscriber/(?P<id>\d+)/$',    'update_subscriber',name='update_subscriber'),

    # Sending messages views
    url(r'^send_message/$',                      'easySend',         name='easySend'),
    url(r'^send_to_channel/$',                   'easySend', {'tipo': 'channel'}, name='easyChannelSend'),

    # Ajax views
    url(r'^ajax_sms_types/$',                                'ajax_filter_typesSms', name='ajaxFilterSms'),
    url(r'^ajax_subscriber/$',                               'ajaxSubscriber',       name='ajaxSubscriber'),
    url(r'^ajax_delete_subscriber/$',                        'ajaxDeleteSubscriber', name='ajaxDeleteSubscriber'),
    url(r'^ajax_new_subscriber/$',                           'ajaxNewSubscriber',    name='ajaxNewSubscriber'),
    url(r'^ajax_size_file_upload/$',                         'ajax_size_file_upload',name='ajaxSizeFileUpload'),
    url(r'^ajax_filter/(?P<type>Individual|Channel)/$',      'ajax_filter',          name='ajaxFilter'),
    url(r'^ajax_gen_filter/(?P<type>Individual|Channel)/$',  'ajax_gen_filter',      name='ajaxGenFilter'),
    url(r'^ajax_num_of_subs/$',                              'ajaxNumOfSubscribers', name='ajaxNumOfSubscribers'),
    url(r'^ajax_channel_list/$',                             'ajaxChannelList',      name='ajaxChannelList'),
    url(r'^ajax_new_channel/$',                              'ajaxNewChannel',       name='ajaxNewChannel'),

    # Other views
    url(r'^message/list/type(?P<type>Individual|Channel)/$', 'messageList2',         name='messagelist'),
    url(r'^message/list/status/(?P<id>\d+)/$',               'channel_msgs_status',  name='message_status'),
    url(r'^message/type(?P<type>Individual|Channel)/(?P<object_id>\d+)/delete/$', 'deleteMessage', name='deletemessage'),
    url(r'^message/read/(?P<id>\d+)/$',                      'read_message_responses', name='read_message_responses'),
    url(r'^message/read/$',                      'read_message_responses', name='read_message_responses'),
)

singularms/web/urls.py
# -*- coding: utf-8 -*-

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',                  'manager.views.index', name='root'),
    url(r'^accounts/login/$',   'manager.views.index', name='login'),
    url(r'^accounts/logout/$',  'manager.views.logout_view', name="logout"),

    url(r'^manager/',           include('manager.urls')),
    url(r'^accounting/',        include('accounting.urls')),
    url(r'^mt/',                include('mt.urls')),
    url(r'^mo/',                include('mo.urls')),
    url(r'^smlog/',             include('smlog.urls')),
    url(r'^ws/',                include('webservice.urls')),
    url(r'^http/',              include('httpservices.urls')),
    url(r'^addressbook/',       include('addressbook.urls')),

    url(r'^admin/(.*)',         admin.site.root),

    url(r'^site_media/(.*)$',   'django.views.static.serve', {'document_root': './media', 'show_indexes': True}),
    url(r'^attachments/(.*)$',  'django.views.static.serve', {'document_root': './media/attachments', 'show_indexes': True}),
)

singularms/web/apps/mt/models.py
# -*- coding: utf-8 -*-

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from django.db.models.signals import post_save, pre_delete, post_delete

from accounting.models import Provider, Access, Customer, Account, Purchase, NONE_STATUS, SENT_STATUS, PROCESSING_STATUS, FAIL_STATUS
from smlog.models import LOGPRIO_LIST
import datetime
import os
import logging
from constants import *

from singular_exceptions import OutOfCredit

_logger = logging.getLogger('galotecnia')

MONTHS_OPTIONS = (
    (1, _('January')),
    (2, _('February')),
    (3, _('March')),
    (4, _('April')),
    (5, _('May')),
    (6, _('June')),
    (7, _('July')),
    (8, _('August')),
    (9, _('September')),
    (10, _('October')),
    (11, _('November')),
    (12, _('December'))
)

OPERATORS_LIST = (
    (0, 'Vodafone'),
    (1, 'Tempos21'),
    (2, 'Lleida.net'),
    (3, 'SitSMS'),
    (4, 'Arsys'),
)

LOGTYPE_LIST = (
    (1, _('auth')),
    (2, _('message')),
    (3, _('platform')),
    # TODO: completar esto y pensarlo
)

def adapt_mobile(mobile):
    mobile = mobile.strip()
    national = mobile.find('+')
    if national == -1:
        return '+34' + mobile
    # Casos +600000000
    if national == 0 and len(str(mobile)) == 10:
        return '+34' + str(mobile)[1:]
    return mobile

class Body(models.Model):
    """
        The body of a SMS
    """
    plainTxt = models.TextField(verbose_name = _('plain text'), blank = False)
    mms = models.BooleanField(verbose_name = _('MMS'), blank = False, default = False)
    encodedMsg = models.TextField(verbose_name = _('encode Message'), blank = True, null = True)

    def size(self):
        return self.mms and len(self.encodedMsg) or len(self.plainTxt)

    def __unicode__(self):
        return self.plainTxt

    class Meta:
        verbose_name = _('Body')
        verbose_name_plural = _('Bodies')

class Attachment(models.Model):
    """
        An attachment for a MMS
    """
    contentType = models.CharField(verbose_name = _('content type'), max_length = 255, blank = False)
    file = models.FileField(verbose_name = _('file'), upload_to = 'attachments/%Y/%m', blank = False)
    body = models.ForeignKey('Body', blank = False, verbose_name = _('body'))

    def __unicode__(self):
        return self.file.name

    def filename (self):
        return os.path.basename (self.file.name)

    class Meta:
        verbose_name = _('attachment')
        verbose_name_plural = _('attachments')


class Channel(models.Model):
    """
        A tematic channel
    """
    name = models.CharField(verbose_name=_('name'), max_length=255, blank=False, unique=True)
    description = models.CharField (verbose_name = _('description'), max_length = 255, blank = False)
    creationDate = models.DateTimeField(verbose_name= _('creation date'), auto_now_add = True, blank = False)
    destructionDate = models.DateTimeField(verbose_name= _('destruction date'), blank = True, null = True)
    active = models.BooleanField(verbose_name= _('active'), blank = False, default = True)
    customer = models.ManyToManyField(Customer, verbose_name=_('customer'), blank=False)

    CHANNEL_DOES_NOT_EXIST = -2000

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['-creationDate']
        verbose_name = _('channel')
        verbose_name_plural = _('channels')
        permissions = ( ("can_manage", "Can manage"), )

    @staticmethod
    def create_one(text, channel_name, account, activationDate, deactivationDate = None):
        """
            Send a sms to a channel
        """

        # Check if channel_name exist
        try:
            channel = Channel.objects.get (name = channel_name)
        except Channel.DoesNotExist:
            return Channel.CHANNEL_DOES_NOT_EXIST

        # Check if we have enough credits and reserve it
        try:
            account.check_credit(True, channel.subscriber_set.count())
        except OutOfCredit:
            return ACCOUNT_NO_CREDIT

        # Check if account can send messages to channel_name
        b = Body(plainTxt=text, mms=False, encodedMsg=text)
        b.save ()
        m = Message(body=b, activationDate=activationDate, account=account, deactivationDate=deactivationDate)
        m.save ()
        cm = ChannelMessage (message = m, channel = channel)
        cm.save()

        return cm.id

class Subscriber(models.Model):
    """
        Mobile number of a person subscribed to the platform
    """
    mobile = models.CharField(verbose_name = _('mobile phone'), max_length=15, blank=False, unique=True)
    name = models.CharField(verbose_name = _('name'), max_length = 255, blank = True, null = True)
    creationDate = models.DateTimeField(verbose_name = _('creation date'), auto_now_add = True, blank = False)
    channels = models.ManyToManyField(Channel, verbose_name = _('channels'))

    def __unicode__(self):
        return self.mobile

    class Meta:
        verbose_name = _('subscriber')
        verbose_name_plural = _('subscribers')

    @staticmethod
    def create(mobile, channel_id, name):
        mob = adapt_mobile(mobile)
        item, created = Subscriber.objects.get_or_create(mobile = mob)
        item.name = name
        item.save()
        ch = Channel.objects.get(pk = channel_id)
        if ch not in item.channels.all():
            item.channels.add(ch)
            item.save()
        post_save.send(sender=Subscriber, instance=item)
        return created

def save_subsc_handler(sender, **kwargs):
    return sub_handler(sender, 
                       lambda u: u + 1,
                       "Instance error in subscriber save signal",
                       **kwargs)

def del_subsc_handler(sender, **kwargs):
    return sub_handler(sender, 
                       lambda u: u - 1,
                       "Instance error in subscriber del signal",
                       **kwargs)

def sub_handler(sender, function, msg, **kwargs):
    ch_id_list = []
    chmsg_list = []
    subsc = None
    try:
        subsc = kwargs['instance']
    except KeyError:
        _logger.error("Error while try to get a Subscriber instance")
        return
    # Subscriber's channels id list
    try:
        for ch in subsc.channels.values():
            ch_id_list.append(ch['id'])
    except AttributeError:
        _logger.error(msg)
        return    

    # Check each subscriber's channel if there is any unprocessed msg
    for ch in Channel.objects.filter(id__in = ch_id_list):
        for chmsg in ch.channelmessage_set.all():
            if not chmsg.message.processed:
                # Looking for a positive purchase
                for p in chmsg.message.account.purchase_set.all():
                    if p.real_credit() > 0:
                        p.reserved = function(p.reserved)
                        p.save()
                        break    

post_save.connect(save_subsc_handler, sender=Subscriber)
pre_delete.connect(del_subsc_handler, sender=Subscriber)

class MessageBase (models.Model):
    """
        The content of a message (previous form of a SMS)
    """
    processed = models.BooleanField(verbose_name=_('processed'), blank = False, default = False)
    body = models.ForeignKey('Body', verbose_name=_('body'), blank = False, null = False)
    creationDate = models.DateTimeField(verbose_name=_('creation date'), auto_now_add = True, blank = False)

    class Meta:
            abstract = True

class Message (MessageBase):
    """
        The content of a message (previous form of a SMS)
    """
    activationDate = models.DateTimeField(verbose_name=_('activation date'), blank = False)
    deactivationDate = models.DateTimeField(verbose_name=_('deactivation date'), blank = True, null = True)
    firstSentDate = models.DateTimeField(verbose_name=_('first sent date'), blank = True, null = True)
    lastSentDate = models.DateTimeField(verbose_name=_('last sent date'), blank = True, null = True)
    account = models.ForeignKey(Account, verbose_name=_('account'))
    mobile = models.CharField(verbose_name = _('mobile phone'), max_length = 15, blank = True, null = True)
    repliable = models.BooleanField(verbose_name = _('Is this message repliable?'), default=False)

    def __unicode__(self):
         return _("%(body)s (m:%(mobile)s)") % {'body':self.body, 'mobile':self.mobile}

    # Return number of message channel subscriptors
    def num_of_phones(self):
        return self.channelmessage_set.all()[0].channel.subscriber_set.all().count()

singularms/web/templates/mt/channel.html
{% extends "base.html" %}

{% comment %}

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

{% endcomment %}

{% load i18n calendar breadcrumbs%}
{% block layout %}
<link rel="stylesheet" type="text/css" media="screen,projection,print" href="{{MEDIA_URL }}/css/layout2_setup.css" />
<link rel="stylesheet" type="text/css" media="screen,projection,print" href="{{MEDIA_URL }}/css/layout2_text.css" />
<link rel="stylesheet" type="text/css"  href="{{MEDIA_URL }}/css/timepicker_plug/css/style.css" />
<link rel="stylesheet" type="text/css"  href="{{MEDIA_URL }}/css/smoothness/jquery-ui-1.7.2.custom.css" />
{% endblock %}

{% block jscript %}
{% include "jqueryui_loader.html" %}
<script src="{{MEDIA_URL}}/jquery/ui/timepicker_plug/timepicker.js" type="text/javascript"></script>
<script src="{{MEDIA_URL}}/jquery/ui/i18n/ui.datepicker-es.js" type="text/javascript"></script>
{% endblock %}
{%block jquerycode %}
<script>

    $(document).ready(function(){
        $('#id_destructionDate').datetime({
									userLang	: 'es'
								});
    });

</script>
{% endblock %}

{% block maincontent %}
    {% ifequal use "create" %}
        <h1 class="pagetitle">{% trans "Create a new channel" %}</h1>
            <h1 class="block">{% trans "Creating a new channel: " %}</h1>
            <div class="column1-unit">
                <h1>{% trans "Please, fill next fields" %}</h1>
    {%else %}
        {% ifequal use "update" %}
            <h1 class="pagetitle">{% trans "Channel's detail" %}</h1>
            <h1 class="block">{% trans "Channel: " %} {{ object.name }}</h1>
            <div class="column1-unit">
                <h1>{% trans "You can modify next fields" %}</h1>
        {%endifequal %}
    {% endifequal %}
			<div class="contactform">
					{% include "mt/channel_form.html" %}
			</div>
		</div>
{% endblock %}

singularms/web/templates/mt/channel_confirm_delete.html
{% extends "base.html" %}
{% load i18n breadcrumbs display_object%}

{% comment %}

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

{% endcomment %}


{% block jscript %}
{% include "jqueryui_loader.html" %}
{% endblock %}


{% block maincontent %}
	<h1 class="pagetitle">{% trans "Channel deletion page" %}</h1>
	{% if object %}
		<h1 class="block">{% trans "Deleting channel: " %} {{ object.name }}</h1>	
		<div class="column1-unit">
			<h1>{% trans "Are you sure that do you want to delete this channel?" %}</h1>
			<div class="contactform">
				<form method="post" action="">
				<fieldset>
					<legend>{% trans "Channel details:" %}</legend>
					<p><label for="id_name" class="left">{% trans "Nombre: " %}</label>
					{{ object.name }}
					</p>
					<p><label for="id_description" class="left">{% trans "Description: " %}</label>
					{{ object.description }}
					</p>
					<p><label for="id_creationdate" class="left">{% trans "Creation date: " %}</label>
					{{ object.creationDate }}
					</p>
					<p><label for="id_active" class="left">{% trans "Activo: " %}</label>
					{{ object.active }}
					</p>
					<p><label for="id_customer" class="left">{% trans "Customer: " %}</label>
					
					{% for customer in object.customer.values %}
 
						{{ customer.username }}
						{% if not forloop.last %}
						,
						{{% endif %} 
					{% endfor %}
					</p>                                   
					<p><input name="submit" id="submit" class="button"
						value= {% trans "Delete" %} 
						tabindex="6" type="submit"/>
					</p>
				</fieldset>
				</form>
			</div>
		</div>
	{% else %}
		<h1 class="block"> {% trans "Channel not found" %} </h1>	
		<div class="column1-unit">
			<h1>{% trans "Selected channel didn't exists" %}</h1>
			<p>
			{% blocktrans %}
				Error: SingularMS didn't found the objects that you have
				requested, please contact with your system administrator.
			{% endblocktrans %}
			</p>
		</div>
	{% endif %}
{% endblock %}

singularms/web/templates/mt/channel_form.html
{% comment %}

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

{% endcomment %}


{% load i18n display_form%}

<form method="post" action="">
	{% if form.has_errors %}
		<h2>{%trans  "Please correct the following error"%}{{ form.error_dict|pluralize }}:</h2>
	{% endif %}

	<fieldset>
		<legend>{% trans "Channel details:" %}</legend>
        {% display_form form  %}
		<p><input name="submit" id="submit" class="button"
  			value= {% trans "Save" %} 
  			tabindex="6" type="submit"/>
		</p>
	</fieldset>
</form>

singularms/web/templates/mt/message_confirm_delete.html
{% extends "base.html" %}

{% comment %}

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

{% endcomment %}

{% load i18n breadcrumbs display_object%}

{% block jscript %}
{% include "jqueryui_loader.html" %}
{% endblock %}


{% block maincontent %}
	<h1 class="pagetitle">{% trans "Message deletion page" %}</h1>
	{% if object %}
		<h1 class="block">{% trans "Deleting message: " %} {{ object.id }}</h1>
		<div class="column1-unit">
			<h1>{% trans "Are you sure that do you want to delete this message?" %}</h1>
			<div class="contactform">
				<form method="post" action="">
				<fieldset>
					<legend>{% trans "Message details:" %}</legend>
					<p><label for="id_creationdate" class="left">{% trans "Creation date: " %}</label>
                    {% ifequal type 'Individual' %}
                        {{ object.creationDate }}
                    {% else %}
                        {{ object.message.creationDate }}
                    {% endifequal %}
					</p>
                    <p>
                        <label for="id_processed" class="left">{% trans "Processed: " %}  </label>
                        {% ifequal type 'Individual' %}
                            {{ object.processed }}
                        {% else %}
                            {{ object.message.processed }}
                        {% endifequal %}
                    </p>
                    <p>
                        <label for="id_account" class="left">{%trans 'Account: '%} </label>
                        {% ifequal type 'Individual' %}
                            {{ object.account }}
                        {% else %}
                            {{ object.message.account }}
                        {% endifequal %}
                    </p>
                    <p>
                    <label for="id_mobile" class="left">{%trans 'Mobile: '%} </label>
                        {% ifequal type 'Individual' %}
                            {{ object.mobile }}
                        {% else %}
                            {{ object.message.mobile }}
                        {% endifequal %}
                    </p>

                    <p>
                        <label for="id_body" class="left">{%trans 'Body: ' %}</label>
                        {% ifequal type 'Individual' %}
                            {{object.body }}
                        {% else %}
                            {{object.message.body }}
                        {% endifequal %}
                    </p>
                    <p>
                        <label for="id_activationDate" class="left">{% trans 'activationDate: ' %}</label>
                        {% ifequal type 'Individual' %}
                            {{object.activationDate}}
                        {% else %}
                            {{object.message.activationDate}}
                        {% endifequal %}
                    </p>
                    <p>
                        <label for="id_deactivationDate" class="left">{%trans 'deactivationDate: ' %}</label>
                        {% ifequal type 'Individual' %}
                            {{object.deactivationDate}}
                        {% else %}
                            {{object.message.deactivationDate}}
                        {% endifequal %}
                    </p>
                    <p>
                        <label for="id_firstSentDate" class="left"> {% trans 'firstSentDate: ' %}</label>
                        {% ifequal type 'Individual' %}
                            {{object.firstSentDate}}
                        {% else %}
                            {{object.message.firstSentDate}}
                        {% endifequal %}
                    </p>
                    <p>
                        <label for="id_lastSentDate" class="left">{% trans 'lastSentDate: ' %}</label>
                        {% ifequal type 'Individual' %}
                            {{object.lastSentDate}}
                        {% else %}
                            {{object.message.lastSentDate}}
                        {% endifequal %}
                    </p>

					<p><input name="submit" id="submit" class="button"
						value= {% trans "Delete" %} 
						tabindex="6" type="submit"/>
					</p>
				</fieldset>
				</form>
			</div>
		</div>
	{% else %}
		<h1 class="block"> {% trans "Channel not found" %} </h1>	
		<div class="column1-unit">
			<h1>{% trans "Selected channel doesn't exist" %}</h1>
			<p>
			{% blocktrans %}
				Error: SingularMS didn't found the objects that you have
				requested, please contact with your system administrator.
			{% endblocktrans %}
			</p>
		</div>
	{% endif %}
{% endblock %}