singularms/web/urls.py
# -*- coding: utf-8 -*-

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic.simple import direct_to_template

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$',                  'manager.views.index', name='root'),
    url(r'^accounts/login/$',   'manager.views.index', name='login'),
    url(r'^accounts/logout/$',  'manager.views.logout_view', name="logout"),

    url(r'^manager/',           include('manager.urls')),
    url(r'^accounting/',        include('accounting.urls')),
    url(r'^mt/',                include('mt.urls')),
    url(r'^mo/',                include('mo.urls')),
    url(r'^smlog/',             include('smlog.urls')),
    url(r'^ws/',                include('webservice.urls')),
    url(r'^http/',              include('httpservices.urls')),
    url(r'^addressbook/',       include('addressbook.urls')),

    url(r'^admin/(.*)',         admin.site.root),

    url(r'^site_media/(.*)$',   'django.views.static.serve', {'document_root': './media', 'show_indexes': True}),
    url(r'^attachments/(.*)$',  'django.views.static.serve', {'document_root': './media/attachments', 'show_indexes': True}),
)

singularms/web/apps/mo/forms.py
# -*- coding: utf-8 -*-

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

from django import forms
from django.contrib.formtools.wizard import FormWizard
from django.utils.translation import ugettext_lazy as _
from django.conf import settings
from smlog.views import debug

from mo.models import IncomingMessage, Command, AdminCommand, ReplyCommand, ExternalCommand, ServiceCore, ServiceArg
from mo.models import ADMIN_COMMAND_TRANSLATION, ADMIN_COMMAND_LIST_CHOICES, getNameFromTuple, EXTERNAL_COMMAND_TYPE_LIST
from mo.models import REPLY, ADMIN, EXTERNAL
from mt.models import Body, Channel

import copy
import string
from libs.limbus.limbus import get_limbus_client
from xml.parsers.expat import ExpatError
from django.utils.datastructures import SortedDict
import datetime

import logging
log = logging.getLogger('galotecnia')

SMS_MAX_LENGTH = 130
ASCII_SPACE = ' '

class bodyTxtField(forms.CharField):
    """
    For a given text, creates a new body instance
    """
    def __init__(self, max_length=SMS_MAX_LENGTH, min_length=None, *args, **kwargs):
        self.max_length, self.min_length = max_length, min_length
        self.widget = forms.Textarea
        super(forms.CharField, self).__init__(*args, **kwargs)

    def clean(self, text):        
        if text is u'':
            return None
        itemTxt = Body(plainTxt=text, mms=False)
        itemTxt.save()
        return itemTxt

# For debug processes only. Should be deleted 
class incomingMsgForm(forms.ModelForm):     
    class Meta: 
        model = IncomingMessage 
               
    def __init__(self, user=None, *args, **kwargs): 
        self.user = user 
        super(forms.ModelForm, self).__init__(*args, **kwargs)

class commandForm(forms.ModelForm):
    defaultAnswer = bodyTxtField(label=_("Default answer"), required=False)
    class Meta:
        model = Command
        exclude = ['id', 'defaultAnswer']
        
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(forms.ModelForm, self).__init__(*args, **kwargs)
        
class replyCommandForm(forms.ModelForm):
    answer = bodyTxtField(label=_("Answer") )
    class Meta:
        model = ReplyCommand
        exclude = ['id']

    def clean(self):
        data = self.cleaned_data
        start = data['startTime']
        end = data['endTime']
        if start >= end:
            raise forms.ValidationError( _("The activation date cant be bigger or same than \
                                            deactivation date") )
        all = ReplyCommand.objects.filter(command = data['command']).order_by('startTime')
        if not all:
            return data
        pre = None
        for rc in all:
            if rc.startTime > end:
                if not pre or start > pre.endTime:
                    return data
            pre = rc
        if start > pre.endTime:
            return data
        raise forms.ValidationError( _("There is a conflict in dates with anothers Reply Commands") )
                    
        
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(forms.ModelForm, self).__init__(*args, **kwargs)        
        
class newCompleteReplyCommandForm(forms.ModelForm):
    """
        Creates both a reply command and a base command
    """
    answer = forms.CharField(label=_("Answer"), widget=forms.Textarea)    
    class Meta:        
        exclude = ['id', 'type', 'defaultAnswer']
        model = Command
        
    def __init__(self, user=None, *args, **kwargs):
        super(forms.ModelForm, self).__init__(*args, **kwargs)        
        self.user = user
        # TODO: Load of bodies needed to be discussed first. 
        #This is perfectly safe for deleting.

    def clean(self):
        data = self.cleaned_data
        start = data['activationDate']
        end = data['deactivationDate']
        if start >= end:
            raise forms.ValidationError( _("The activation date cant be bigger or same than \
                                            deactivation date") )
        cmd = None
        try:
            cmd = Command.objects.get(pattern = data['pattern'])
        except Command.DoesNotExist:
            return data
        all = ReplyCommand.objects.filter(command = cmd.id).order_by('startTime')
        if not all:
            return data
        pre = None
        for rc in all:
            if rc.startTime > end:
                if not pre or start > pre.endTime:
                    return data
            pre = rc
        if start > pre.endTime:
            return data
        raise forms.ValidationError( _("There is a conflict in dates with anothers Reply Commands") )
 
    def save(self, commit=True):
        try:
            itemCommand = Command.objects.get(pattern = self.cleaned_data['pattern'])
            if itemCommand.activationDate > self.cleaned_data['activationDate']:
                itemCommand.activationdate = self.cleaned_data['activationDate']
            if itemCommand.deactivationDate < self.cleaned_data['deactivationDate']:
                itemCommand.deactivationDate = self.cleaned_data['deactivationDate']
        except Command.DoesNotExist:
            itemCommand = super(forms.ModelForm, self).save(commit=False)
        itemCommand.type = REPLY    #type: ReplyCommand
        itemCommand.defaultAnswer = None
        if commit:
            itemCommand.save()
            itemTxt = Body(plainTxt=self.cleaned_data['answer'], mms=False)
            itemTxt.save()
            itemReplyCommand = ReplyCommand(command=itemCommand, startTime=self.cleaned_data['activationDate'], 
                                            endTime=self.cleaned_data['deactivationDate'], answer=itemTxt)
            itemReplyCommand.save()
        return itemCommand

# Admin forms ------------------------------------------------------------------------------        
class adminCommandForm(forms.ModelForm):
    class Meta:
        model = AdminCommand
    
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(adminCommandForm, self).__init__(*args, **kwargs)
        
class singleAdminCommandForm(forms.ModelForm):
    """
        Creates both an admin command and a base command. Handles the language correctly.
    """
    action = forms.ChoiceField(choices=ADMIN_COMMAND_LIST_CHOICES, label=_('Action') )
    language = None
    channel = forms.ChoiceField()
    answer = forms.CharField(label=_("Default Answer"), widget=forms.Textarea, max_length = 160, required=False)    
    
    class Meta:
        model = Command
        exclude = ['pattern', 'type', 'defaultAnswer']
        
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        try:
            self.language = kwargs['language']
            del kwargs["language"]
        except KeyError:
            pass
        super(singleAdminCommandForm, self).__init__(*args, **kwargs)               
        self.channelChoices = []
        for channel in Channel.objects.filter(active=True):
            self.channelChoices.append((channel.id, channel.name) )            
        self.fields['channel'] = forms.ChoiceField(choices=self.channelChoices)
 
    def clean(self):
        data = self.cleaned_data
        deactiDate = data['deactivationDate']
        if not deactiDate:
           return data
        actiDate = data['activationDate']
        if actiDate >= deactiDate:
            raise forms.ValidationError( _("The activation date cant be bigger or same than \
                                            deactivation date") )
        return data      
 
    def save(self, commit=True):
        instance = super(singleAdminCommandForm, self).save(commit=False)
        instance.type = ADMIN
        ans = Body(plainTxt = self.cleaned_data['answer'])
        ans.save()
        instance.defaultAnswer = ans
        # Getting a translation if available
        try:
            index = int(self.cleaned_data['action'])            
            actionName = getNameFromTuple(ADMIN_COMMAND_LIST_CHOICES, index)
            translatedCommandType = ADMIN_COMMAND_TRANSLATION[self.language][actionName]
        except KeyError:
            translatedCommandType = actionName
             
        channel = Channel.objects.get(pk=self.cleaned_data['channel'])
        instance.pattern = translatedCommandType + ASCII_SPACE + channel.name                
        if commit:
            # Already existing commands are deleted
            try:
                oldcommand = Command.objects.get(pattern=instance.pattern)

singularms/web/templates/jquery/body_charcounter.html
{% comment %}

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

{% endcomment %}

{% load i18n %}
<script type="text/javascript" src="{{ MEDIA_URL }}/jquery/jquery.charcounter.js"></script>
<script type="text/javascript">
	// Constants block
	var MAX_CHAR = 160
    $(document).ready(function() {
        $("#id_defaultAnswer, #id_answer").charCounter(MAX_CHAR, {
			container: "<help_text>",
			format: "(%1 {% trans 'characters remaining' %})"
		});
    })
</script>

singularms/web/templates/jquery/datepicker.html
{% comment %}

#######################################################################
#  SingularMS version 1.0                                             #
#######################################################################
#  This file is a part of SingularMS.                                 #
#                                                                     #
#  SingularMs is free software; you can copy, modify, and distribute  #
#  it under the terms of the GNU Affero General Public License        #
#  Version 1.0, 21 May 2007.                                          #
#                                                                     #
#  SingularMS is distributed in the hope that it will be useful, but  #
#  WITHOUT ANY WARRANTY; without even the implied warranty of         #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               #
#  See the GNU Affero General Public License for more details.        #
#                                                                     #
#  You should have received a copy of the GNU Affero General Public   #
#  License with this program; if not, contact Galotecnia              #
#  at contacto[AT]galotecnia[DOT]org. If you have questions about the #
#  GNU Affero General Public License see "Frequently Asked Questions" #
#  at http://www.gnu.org/licenses/gpl-faq.html                        #
#######################################################################

{% endcomment %}

<script type="text/javascript">  
    $(document).ready(function() {
        // Fields which use date time picker.
        $('#id_actiDate').datetime({userLang: 'es'});
        $("#id_deactiDate").datetime({userLang: 'es'});
        $("#id_startDate").datetime({userLang: 'es'});
        $("#id_endDate").datetime({userLang: 'es'});
        // Se podría usar un for para esto?
        $("#id_activationDate").datetime({userLang: 'es'});
        $("#id_deactivationDate").datetime({userLang: 'es'});
        $("#id_0-activationDate").datetime({userLang: 'es'});
        $("#id_0-deactivationDate").datetime({userLang: 'es'});//id_2-startDate
        $("#id_2-startDate").datetime({userLang: 'es'});
        $("#id_2-endDate").datetime({userLang: 'es'});
        // ******
        $("#id_startTime").datetime({userLang: 'es'});
        $("#id_endTime").datetime({userLang: 'es'});        
    })
</script>